### ISSUE TITLE
Send is not working with files heavier than 1Mo

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/bitwarden_ynh#125]
### Describe the bug

I tried the send functionality via the web interface and via the firefox extension, without success when I try to send files heavier than 1Mo (1.1Mo is enough to fail).

### Context

- Hardware: *computer*
- YunoHost version: 4.1.7.4
- Using: master / 1.20

### Steps to reproduce
In the web interface or via FireFox extension, try to send a file
![image](https://user-images.githubusercontent.com/693751/113299954-b706f600-92fd-11eb-8f38-e3c379f09b2c.png)

When only text is sent, it works perfectly.
It also works perfectly with files less than 1Mo

**Comment by supermamie** [comment]
The fix is for files of 50M, but all interfaces display a 100M max.

**Comment by supermamie** [comment]
Here are screenshots of the web UI 
![image](https://user-images.githubusercontent.com/693751/113404096-ec681e00-93a7-11eb-9106-1e9466aa28c3.png)

And the Firefox module
![image](https://user-images.githubusercontent.com/693751/113404156-ff7aee00-93a7-11eb-832e-4c3e43aaf8d0.png)

(It seems that I can not open the issue again, @yalh76 should I open a new one ? )

**Comment by yalh76** [comment]
solved ^^ I hope
