### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/bitwarden_ynh#24]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/ci/job/5756

Your app will be moved at 'notworking' status by the end of next week, on January, 4 if nothing is done before to make it work.

**Comment by yalh76** [comment]
Currently working on it.
Last OR:https://github.com/YunoHost-Apps/bitwarden_ynh/pull/23 was ok on my CI

**Comment by kay0u** [comment]
You should switch your app as working then :-)

**Comment by yalh76** [comment]
I was waiting https://ci-apps.yunohost.org/ci/apps/bitwarden/ results before, but first package_check failed :/ 

Need to do more tests

**Comment by yalh76** [comment]
Well, I have done a lot of package_check on bitwarden_ynh. All are ok and level7. 
But I still don't understand why [ci-apps](https://ci-apps.yunohost.org/ci/apps/bitwarden/) still fails.

Here are results from my CI
![image](https://user-images.githubusercontent.com/30271971/72687373-6989d900-3afd-11ea-86c8-17e1a4f6e71c.png)
![image](https://user-images.githubusercontent.com/30271971/72687381-7d353f80-3afd-11ea-8261-8599232ad0ac.png)

Here a result from a freshly installed package_check
![image](https://user-images.githubusercontent.com/30271971/72687382-8a522e80-3afd-11ea-981a-c9f6fe8662fb.png)

**Comment by maniackcrudelis** [comment]
You should try to use the --time argument on ynh_script_progression to see how much time the service take to start. And how much there is before the script end after that.
I suspect something about that, the official CI isn't especially fast.

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost-Apps/bitwarden_ynh/pull/42/files#diff-44cb16c778719320333118c04d509a7cR169-R172
THIS IS NOT A SOLUTION !!!

Find and fix the issue !

**Comment by maniackcrudelis** [comment]
As the error is "failed to spawn thread", you should look about number of workers, which can be set (somewhere) for Rust.
https://docs.rs/rocket/0.3.12/rocket/struct.Config.html#structfield.workers
The repo you're using use the env variable `ROCKET_WORKERS` with docker (https://github.com/dani-garcia/bitwarden_rs/wiki/Changing-the-number-of-workers). Could be a lead.

**Comment by yalh76** [comment]
Thanks a lot, I will try that.

**Comment by yalh76** [comment]
Thanks for the help after implementing ROCKET_WORKERS and reducing to ROCKET_WORKERS=1 package_check is now ok. But I really don't know what will be the effect on production. We will see :)
