### ISSUE TITLE
Big backup file

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/bitwarden_ynh#46]
I don't really know how or why, but my Bitwarden backup is ~5GB.
I know I have many passwords stored inside, maybe a few hundreds, but nowhere near 5GB.
Just to compare, my keepass file I used before was 122kB
So I think way more things are backuped than necessary
I just tried to check the space used in /var/www/bitwarden :

```
678M	build
2,7G	live
	21M	bitwarden_rs
	8,0K	bitwarden_rs.d
	12K	bitwarden_rs.env
	559M	build
	7,8M	data
	2,1G	deps
	4,0K	examples
	4,0K	incremental
	4,0K	native
	56M	web-vault
```

Isn't only "web-vault" necessary ? (or "data" maybe ?, but the rest could be re-build ?)

**Comment by yalh76** [comment]
YunoHost is not just a backup of the database where the password are stored. It's the backup of the complete application to be able to reinstall identically it on your server or another server.

The database of the password is stored in the directory `data`
