### ISSUE TITLE
failt to upgrade

### ISSUE THREAD

**Issue by fabianski7** [YunoHost-Apps/bitwarden_ynh#56]
I was trying to update bitwarden from 1.13.1 ~ ynh1 to 1.14 ~ ynh1 but an error occurs during this process.

Here are the logs generated by yunohost https://paste.yunohost.org/raw/axunajuyug

**Comment by yalh76** [comment]
It seems that your YunoHost lack of memory .. How many ram do you have ?
Did someone else had that issue ?

**Comment by fabianski7** [comment]
it's a simple vps. only 1gb of ram

**Comment by yalh76** [comment]
And you have a lot of apps installed ?
Maybe you should add swap to your Yunohost: https://yunohost.org/#/troubleshooting_guide_en

**Comment by fabianski7** [comment]
i created the swap file, now the update works.
thanks.
