### ISSUE TITLE
FAIL TO OPEN

### ISSUE THREAD

**Issue by yoyomimo** [YunoHost-Apps/bitwarden_ynh#59]
Hello,

I justed Instal BitWarden, when  I go to the link I had "Le délai d’attente est dépassé" from my browser. But the other APS work. I'm on 3.7 of yunohost.

:)

**Comment by yalh76** [comment]
Can you access the command line and do `service bitwarden status` ?

**Comment by ericgaspar** [comment]
I too cannot connect to Bitwarden.
`service bitwarden status` gives me:

> Apr 24 18:03:17 domain.fr bitwarden_rs[449]: Error: Unauthorized Error: Invalid claim
> Apr 24 18:03:17 domain.fr bitwarden_rs[449]: Warning: Responding with 401 Unauthorized catcher.

**Comment by yalh76** [comment]
> 
> 
> I too cannot connect to Bitwarden.
> `service bitwarden status` gives me:
> 
> > Apr 24 18:03:17 domain.fr bitwarden_rs[449]: Error: Unauthorized Error: Invalid claim
> > Apr 24 18:03:17 domain.fr bitwarden_rs[449]: Warning: Responding with 401 Unauthorized catcher.

Have you checked https://github.com/YunoHost-Apps/bitwarden_ynh/issues/3 ?

**Comment by ericgaspar** [comment]
Thanks👍I will reinstall as public
