### ISSUE TITLE
__ADMIN_TOKEN__ not found (but in the log :)

### ISSUE THREAD

**Issue by eenbroleke** [YunoHost-Apps/bitwarden_ynh#67]
Hi,
thanks for maintaining this app in yunohost.

I've just installed it (yn:3.7.1.1, bw:2.13.2) but I never received the admin token by email (as suggested in the log message).

I could find it through the /var/log/yunohost/yunohost-api*log (with the sed --in-place command used to change the value with __ADMIN_TOKEN__).

Am I missing something obvous here ?
Thanks,

**Comment by alexAubin** [comment]
>I never received the admin token by email (as suggested in the log message).

I believe it should be sent to the root mailbox (which is actually an alias to the first user you created, supposedly .... Except maybe if you deleted the first user you created, not sure what happens then ..)

Did you check that ?

**Comment by eenbroleke** [comment]
you're right, that's my bad.
