### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by zbam** [YunoHost-Apps/bitwarden_ynh#7]
For some reason, I can't install bitwarden, it raises an error. 
journal historisé : https://framabin.org/p/?18a051f00cec0e53#4+hTpjGXAo6u3VnwHVG9wzFlvdn5YuVJne4CUaIFcrE=

**Comment by yalh76** [comment]
Bitwarden require a dedicated root domain, eg. bitwarden.domain.tld
You are trying to install it on an already use by your syncthing.....
