### ISSUE TITLE
Use ~ynh× in version number

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/bitwarden_ynh#77]
Each commit on master generate a new version upgrade in YunoHost.
When there is no software update, there should be a ~ynh1, ~ynh2, etc… version upgrade (so it is possible to check what the upgrade will bring, for example I do not need the last commit)

This si what I have now in my admin console and it seems that there is nothing to upgrade.
![image](https://user-images.githubusercontent.com/693751/83860484-9b53b300-a71f-11ea-91b9-bb55a360df28.png)

**Comment by yalh76** [comment]
I forgot to increase ~ynh1 to ~ynh2
