### ISSUE TITLE
[support] Config redirect

### ISSUE THREAD

**Issue by nr458h** [YunoHost-Apps/bitwarden_ynh#8]
Hi I use a xxx.nohost.me domain. As bitwarden needs a subdomain I installed it to xxx.xxx.local and now I'm stucked trying to configure the redirect via my nohost.me but it always failed until now.

So I would like to ask, what I need to do to get the redirect works?

Thanks in advance

**Comment by yalh76** [comment]
No solution, you have to buy a domain name to host your YunoHost
