### ISSUE TITLE
version number ?

### ISSUE THREAD

**Issue by boistordu** [YunoHost-Apps/bitwarden_ynh#86]
Does your version number related to the bitwarden server version number ? or is It just an adaptation?
and if it is related, do you think that it would be possible with newer version, the install process would be less heavy in ressources?

**Comment by yalh76** [comment]
> Does your version number related to the bitwarden server version number ? or is It just an adaptation?
The version number is related to https://github.com/dani-garcia/bitwarden_rs version number

> and if it is related, do you think that it would be possible with newer version, the install process would be less heavy in ressources? 

Until upstream app: https://github.com/dani-garcia/bitwarden_rs doesn’t provide builds for x64, arm64, the install or upgrade process imply to compile the whole rust server.

**Comment by boistordu** [comment]
is there anyway that we could think off to divide the work somehow? because the problem is that there is a building up in terms of RAM. 
Where c compiler or node compiler in general give us some rest between compilation of modules. Becuase each times it releases the RAM and take it back again to create another module. Here it's a long and continuous building up where the RAM got needed and needed more and more. 
And after all, it's not that big of a webapp to make it run. It's not like gitlab or anything alike.
So do you think it would be possible to separate the compilation process into smaller modules ?

**Comment by yalh76** [comment]
Here is just the Bitwarden package for YunoHost, if you want to speak about the way bitwarden in rust is implemented, go to the upstream app: https://github.com/dani-garcia/bitwarden_rs
