### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by uyouthe** [YunoHost-Apps/bitwarden_ynh#96]
Here's the log: [https://paste.yunohost.org/raw/eliginehoq](https://paste.yunohost.org/raw/eliginehoq).

**Comment by alexAubin** [comment]
```
process didn't exit successfully: `rustc [...]` (signal: 9, SIGKILL: kill)
```

That sounds a lot like your server ran out of RAM and killed that (probably)-heavy-memory consuming process :/

**Comment by uyouthe** [comment]
Scaled to 2GB RAM, installation went fine. Scaled back to 1GB and was able to see the vault login page. Now I'm trying to fix that immediate expiration issue but I guess this has nothing to do with my original issue.

@alexAubin thanks! I'm closing this.
