### ISSUE TITLE
Don't Receive At the end of the installation admin_token used to access

### ISSUE THREAD

**Issue by arnaudbagnis** [YunoHost-Apps/bitwarden_ynh#97]
Hello, I have not received the token to configure my server. Would he have a solution to recover the token in logs or simply regenerate it?

**Comment by alexAubin** [comment]
As a workaround you may be able to get it from the app settings : 

```
grep "admin_token" /etc/yunohost/apps/bitwarden/settings.yml
```

**Comment by arnaudbagnis** [comment]
thanks it's good !
