### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by MatGamedu56** [YunoHost-Apps/bitwarden_ynh#99]
After installing the bitwarden application I wanted to create an account for myself but I have the impression that account creation is disabled, a red rectangle tells me this : registration not allowed or user already exist !

**Comment by TheNomad11** [comment]
Yeah, there is no information about how to use Bitwarden. It seems one has to invite onself. This worked for me. But then the login does not work due to a bug, so currently Bitwarden does not seem to be working and might be considered removed from the app listing

**Comment by Thovi98** [comment]
Go to your admin page --> General settings --> Allow signups --> Set it true --> Create your account --> Log in --> If you want, Set allow signups to false. 
I don’t know if that helps ? It was successful for me.

**Comment by yalh76** [comment]
Yep, you should receive a email at the roo@yourdomain to give you the master password to let you invite other mates.
